refactor:ci tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -98,13 +98,12 @@ jobs:
           echo "Mockoon failed to start"
           exit 1
 
-      - name: Test Splunk is ready
-        run: |
-          EXPECTED="Ansible playbook complete, will begin streaming splunkd_stderr.log"
-          docker logs splunk 2>&1 | tail -n 20 | grep -F "$EXPECTED" && echo "Found expected line near end of logs." || (echo "Expected line not found." && exit 1)
-
       - name: Test connectivity from Splunk to Mockoon
         run: |
+          echo "Test whether Splunk is ready"
+          EXPECTED="Ansible playbook complete, will begin streaming splunkd_stderr.log"
+          docker logs splunk 2>&1 | tail -n 20 | grep -F "$EXPECTED" && echo "Found expected line near end of logs." || (echo "Expected line not found." && exit 1)
+          echo "Test connectivity"
           docker exec splunk curl -v http://mockoon:3004/ || echo "Failed to reach Mockoon from Splunk"
 
       - name: Run integration tests
@@ -118,20 +117,19 @@ jobs:
 
       - name: Run functional tests
         if: success()
-        id: ftests
         env:
           GENESYSCLOUD_HOST: ${{ env.GENESYSCLOUD_HOST }}
         run: |
           python -m pytest modinput_functional/* --junitxml=junit/test-results-${{ matrix.version }}.xml
         working-directory: ./tests
 
-      - if: always()
+      - name: Exporting Mockoon logs
+        if: always()
         run: |
           mkdir -p logs/
           docker logs mockoon > ${{ github.workspace }}/logs/mockoon.log 2>&1
 
       - name: Upload Mockoon logs
-        # if: ${{ steps.ftests.conclusion == 'failure' }}
         if: always()
         uses: actions/upload-artifact@v4
         with:
